{
 "title": "StoredSafe - Security & Policy",
 "description": "Detailed security, policy and authentication metrics.\nUse this dashboard to investigate violations, warnings and abnormal user behavior.",
 "tags": [
  "storedsafe",
  "security"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Warnings",
   "type": "stat",
   "description": "Indicates whether one or more warnings are currently active.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storedsafe_policy_warnings_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "description": "Total number of detected warnings currently active.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storedsafe_policy_warnings_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No-auth warnings",
   "type": "stat",
   "description": "Indicates whether authentication-less access warnings are currently present.\nA value of 1 means at least one no-auth warning is active.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storedsafe_policy_noauth_warnings",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No-auth warnings (count)",
   "type": "stat",
   "description": "Total number of detected authentication-less access warnings currently active.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storedsafe_policy_noauth_warnings_total",
     "legendFormat": "{{license_overrun}}"
    }
   ]
  },
  {
   "title": "Policy violations",
   "type": "stat",
   "description": "Indicates whether one or more policy violations are currently active.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "storedsafe_policy_violations", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Policy violations",
   "type": "stat",
   "description": "Total number of detected policy violations currently active.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storedsafe_policy_violations_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRL Valid",
   "type": "stat",
   "description": "Indicates whether the CRL file is malformed or unreadable.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "storedsafe_crl_invalid_file", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CRL expired",
   "type": "stat",
   "description": "Indicates whether the CRL has expired and is no longer valid.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "storedsafe_crl_expired", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CRL Signature",
   "type": "stat",
   "description": "Indicates whether the CRL signature validation failed.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "storedsafe_crl_invalid_signature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRL fetch error",
   "type": "stat",
   "description": "Indicates whether the CRL file is malformed or unreadable.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "storedsafe_crl_fetch_error", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logins (last 7 days)",
   "type": "bargauge",
   "description": "Total number of successful user login events during the last 7 days.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "storedsafe_stats7d_login", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Decrypt operations (last 7 days)",
   "type": "bargauge",
   "description": "Total number of decrypt operations performed during the last 7 days.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "storedsafe_stats7d_decrypt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Vaults created (last 7 days)",
   "type": "bargauge",
   "description": "Number of vaults created during the last 7 days.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storedsafe_stats7d_vaults_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vaults deleted (last 7 days)",
   "type": "bargauge",
   "description": "Number of vaults deleted during the last 7 days.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storedsafe_stats7d_vaults_deleted",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Objects created (last 7 days)",
   "type": "bargauge",
   "description": "Number of objects created during the last 7 days.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storedsafe_stats7d_objects_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Objects deleted (last 7 days)",
   "type": "bargauge",
   "description": "Number of objects deleted during the last 7 days.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storedsafe_stats7d_objects_deleted",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication failures (7d)",
   "type": "timeseries",
   "description": "Shows the number of failed authentication attempts over the last 7 days. \nSpikes may indicate incorrect credentials, misconfigurations, or attempted unauthorized access.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "storedsafe_stats7d_auth_failure",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weak passphrases detected (7d)",
   "type": "timeseries",
   "description": "Shows the number of detected weak passphrases over the last 7 days. \nSpikes may indicate policy violations, user behavior issues, or onboarding activity.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "storedsafe_stats7d_weak_passphrase",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}